version: '3.7'

services:
  api:
    build: .
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_ENABLE: ${MAIL_ENABLE}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      LOGS_DESTINATION: /var/logs
    volumes:
      - m2:/root/.m2/repository
      - ./logs/:/var/logs
  postgres:
    image: postgres:10.9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      PGDATA: /var/database/postgres/data

volumes:
  m2: