version: '3.7'

services:
  postgres:
    image: postgres:10.9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      PGDATA: /var/database/postgres/data