version: '3.7'

services:
  api:
    build: .
    env_file:
      - .env
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      LOGS_DESTINATION: /var/logs
    volumes:
      - m2:/root/.m2/repository
      - ./logs/:/var/logs
  postgres:
    image: postgres:10.9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      PGDATA: /var/database/postgres/data

volumes:
  m2: