server:
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: "off"
  datasource:
    url: @docker.env.postgres.jdbc.url@
    username: @docker.env.postgres.user@
    password: @docker.env.postgres.password@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: true
  mail:
    host: @docker.env.mail.host@
    port: @docker.env.mail.port@
    username: @docker.env.mail.user@
    password: @docker.env.mail.password@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
docker:
  env:
    mail:
      enable: @docker.env.mail.enable@
jwt:
  secret: @jwt.secret@
  lifeTimeInDays: @jwt.lifeTimeInDays@

liquibase:
  contexts: @docker.env.liquibase.context@