server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: @docker.env.postgres.jdbc.url@
    username: @docker.env.postgres.user@
    password: @docker.env.postgres.password@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate:format_sql: true

jwt:
  secret: @jwt.secret@
  lifeTimeInDays: @jwt.lifeTimeInDays@